USE [DX_KMS]
GO

/****** Object:  Table [dbo].[KMS_M_ROLES]    Script Date: 07/05/2024 17:24:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[KMS_M_ROLES](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[role] [varchar](100) NOT NULL,
 CONSTRAINT [PK_KMS_M_Roles] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

