USE [DX_KMS]
GO

/****** Object:  Table [dbo].[KMS_M_PACKAGE_COURSES]    Script Date: 07/05/2024 17:20:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[KMS_M_PACKAGE_COURSES](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[course_id] [int] NOT NULL,
	[trainer_npk] [varchar](50) NOT NULL,
	[package_id] [int] NOT NULL,
	[durasi] [int] NULL,
 CONSTRAINT [PK_KMS_M_Package_Courses_1] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

