USE [DX_KMS]
GO

/****** Object:  Table [dbo].[KMS_M_USERS]    Script Date: 07/05/2024 17:24:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[KMS_M_USERS](
	[npk] [varchar](50) NOT NULL,
	[nama] [varchar](max) NOT NULL,
	[role] [int] NOT NULL,
 CONSTRAINT [PK_KMS_M_Users] PRIMARY KEY CLUSTERED 
(
	[npk] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

