USE [DX_KMS]
GO

/****** Object:  Table [dbo].[KMS_M_PACKAGE_ASSIGMENT]    Script Date: 07/05/2024 17:19:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[KMS_M_PACKAGE_ASSIGMENT](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[trainee_npk] [varchar](50) NOT NULL,
	[package_id] [int] NOT NULL,
	[class] [varchar](50) NULL,
 CONSTRAINT [PK_KMS_M_Package_Assigment] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

